require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name.start_with?("RCT-Folly")
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      else
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
    if target.name == "React-Core.common-AccessibilityResources"
      target.remove_from_project
    end
    if target.name == "React-Core-AccessibilityResources"
      target.remove_from_project
    end
  end
end

target 'Ev3nt' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )



  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'Ev3ntTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'Ev3nt-tvOS' do
  # Pods for Ev3nt-tvOS

  target 'Ev3nt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
